### ISSUE TITLE
A couple quick questions

### ISSUE THREAD

**Issue by NULLProtogen** [schenkzoola/NES#1]
I'm not sure if I'm missing something but why are there a bunch of capacitors at the bottom going from 5v to ground? Also, is there a reason that U3 (74LS139) is split up into 2 chips?

**Comment by schenkzoola** [comment]
Those capacitors represent the bypass capacitors scattered along the board.  Drawing them all in one place is a tactic to simplify the schematic representation.

U3 is split up because it has two identical demultiplexers contained within the same chip. They don't have to be used for the same function, or even the same part of the circuit.
